// Copyright 2023 daz-3ux(Daz) <daz-3ux@proton.me>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/Daz-3ux/dCache.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.4
// source: dCachePB/dCachePB.proto

package dCachePB

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DCacheRequest) Reset() {
	*x = DCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dCachePB_dCachePB_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DCacheRequest) ProtoMessage() {}

func (x *DCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dCachePB_dCachePB_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DCacheRequest.ProtoReflect.Descriptor instead.
func (*DCacheRequest) Descriptor() ([]byte, []int) {
	return file_dCachePB_dCachePB_proto_rawDescGZIP(), []int{0}
}

func (x *DCacheRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *DCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DCacheResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DCacheResponse) Reset() {
	*x = DCacheResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dCachePB_dCachePB_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DCacheResponse) ProtoMessage() {}

func (x *DCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dCachePB_dCachePB_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DCacheResponse.ProtoReflect.Descriptor instead.
func (*DCacheResponse) Descriptor() ([]byte, []int) {
	return file_dCachePB_dCachePB_proto_rawDescGZIP(), []int{1}
}

func (x *DCacheResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_dCachePB_dCachePB_proto protoreflect.FileDescriptor

var file_dCachePB_dCachePB_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x50, 0x42, 0x2f, 0x64, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x50, 0x42, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x50, 0x42, 0x22, 0x37, 0x0a, 0x0d, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x26, 0x0a, 0x0e,
	0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x32, 0x46, 0x0a, 0x0a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x12, 0x38, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x64, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x50, 0x42, 0x2e, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x50, 0x42, 0x2e, 0x64, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65, 0x50, 0x42, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_dCachePB_dCachePB_proto_rawDescOnce sync.Once
	file_dCachePB_dCachePB_proto_rawDescData = file_dCachePB_dCachePB_proto_rawDesc
)

func file_dCachePB_dCachePB_proto_rawDescGZIP() []byte {
	file_dCachePB_dCachePB_proto_rawDescOnce.Do(func() {
		file_dCachePB_dCachePB_proto_rawDescData = protoimpl.X.CompressGZIP(file_dCachePB_dCachePB_proto_rawDescData)
	})
	return file_dCachePB_dCachePB_proto_rawDescData
}

var file_dCachePB_dCachePB_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dCachePB_dCachePB_proto_goTypes = []interface{}{
	(*DCacheRequest)(nil),  // 0: dCachePB.dCacheRequest
	(*DCacheResponse)(nil), // 1: dCachePB.dCacheResponse
}
var file_dCachePB_dCachePB_proto_depIdxs = []int32{
	0, // 0: dCachePB.GroupCache.Get:input_type -> dCachePB.dCacheRequest
	1, // 1: dCachePB.GroupCache.Get:output_type -> dCachePB.dCacheResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dCachePB_dCachePB_proto_init() }
func file_dCachePB_dCachePB_proto_init() {
	if File_dCachePB_dCachePB_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dCachePB_dCachePB_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dCachePB_dCachePB_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DCacheResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dCachePB_dCachePB_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dCachePB_dCachePB_proto_goTypes,
		DependencyIndexes: file_dCachePB_dCachePB_proto_depIdxs,
		MessageInfos:      file_dCachePB_dCachePB_proto_msgTypes,
	}.Build()
	File_dCachePB_dCachePB_proto = out.File
	file_dCachePB_dCachePB_proto_rawDesc = nil
	file_dCachePB_dCachePB_proto_goTypes = nil
	file_dCachePB_dCachePB_proto_depIdxs = nil
}
